matrix:
  include:
    language: php
    php:
    - '7.1'
    dist: trusty
    addons:
      chrome: stable
    sudo: required
    services:
    - mysql
    cache:
      directories:
      - "$HOME/.composer/cache/files"
    env:
    - SYMFONY_VERSION="3.4.*" DB=mysql
    - NODE_RELEASE=8.x
    before-install:
    # php
    - composer self-update
    # node
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    install:
    # php
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - cp www/app.php.example www/app.php
    - composer install
    - composer update
    - php bin/console doctrine:database:create
    - php bin/console doctrine:schema:update --force
    - php bin/console doctrine:fixtures:load -n
    # node
    - cd wn-frontend
    - sudo rm -rf ~/.nvm
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - node -v
    - npm install
    - cd ..
    before_script:
    # php
    - sudo apt-get update
    - sudo apt-get install apache2
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart
    # node (fix for chrome not starting on travis ci)
    - sudo chown root /opt/google/chrome/chrome-sandbox
    - sudo chmod 4755 /opt/google/chrome/chrome-sandbox
    script:
    # php
    - php vendor/bin/simple-phpunit
    - cd wn-frontend
    # node
    - npm run test
    - npm run build
    - cd ..
    after_script:
    # php
    - mkdir -p build/logs
    - php vendor/bin/php-coveralls --dry-run -v
    # node
    - cd wn-frontend
    - node merge-coveralls-json.js
notifications:
  email:
    recipients:
    - the_weirdo@gmx.net
    on_success: always