matrix:
  include:
    language: php
    php:
    - '7.1'
    dist: trusty
    addons:
      chrome: stable
    sudo: false
    services:
    - mysql
    cache:
      directories:
      - "$HOME/.composer/cache/files"
    env:
    - SYMFONY_VERSION="3.4.*" DB=mysql
    - NODE_RELEASE=8.x
    before-install:
    # php
    - composer self-update
    install:
    # Set tip of branch to head of active branch
    - git checkout ${TRAVIS_BRANCH}
    # php
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - cp www/app.php.example www/app.php
    - composer install
    - composer update
    - mysql -e "CREATE DATABASE WerftnetTest CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
    - mysql -e "CREATE USER 'test'@'localhost' IDENTIFIED BY 'test';"
    - mysql -e "GRANT ALL PRIVILEGES ON WerftnetTest.* TO 'test'@'localhost' IDENTIFIED BY 'test';"
    # node
    - cd wn-frontend
    - sudo rm -rf ~/.nvm
    - curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
    - sudo apt-get install -y nodejs
    - node -v
    - npm install
    - cd ..
    before_script:
    # php
    - sudo apt-get update
    - sudo apt-get install apache2
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart
    script:
    # php
    - php vendor/bin/simple-phpunit
    - cd wn-frontend
    # node
    - npm run test
    - npm run build
    - cd ..
    after_script:
    # php
    - mkdir -p build/logs
    - php vendor/bin/php-coveralls --dry-run -v
    # node
    - cd wn-frontend
    - node merge-coveralls-json.js
notifications:
  email:
    recipients:
    - the_weirdo@gmx.net
    on_success: always