matrix:
  include:
  - stage: backend
    language: php
    php:
    - '7.1'
    sudo: false
    services:
    - mysql
    cache:
      directories:
      - "$HOME/.composer/cache/files"
    env:
    - SYMFONY_VERSION="3.4.*" DB=mysql
    - secure: iQCFbpx/znsTP8V+NsHjzlN8LhObpt5u/7qOheVjssLu6aeAIgEicm138J+fMjrpj7hlQgmxOWKzXLAm9K3mG6onAN7Xj3gH7tbo7HTwGeKibmCuzSaZ3fcVllS1vyj+c7c2RlbcMTiUKge07a3b4btEk4kk32EtjvBh57vp/vs+Qq2C+rIBNmdqJLwLgdqfU+49Ua+1FBo7x2syqHISKNdtZni61oywphGaNMz8zrVQTECFgmBKjK8aw+7ghcVs8eWMz6oHuB8IiCS4aeDVvIOfRRqj52cUv64Q5fZTSAW+EbwxV75w8zc0kY6pL5fOWcaTR2pEHAwSoBvvS14jE+5EBhBV8L+ycQPdDCHSaffVpCHXcNgAsiyZIJc9WTPLD0O0IChFcUoRFODErenEt8c1ucazuAbOWikTw8xUQvWH/hZ2teKjy6AYStnDbXywaoAB36O3SIPTt7PCwA+LPtTpMkerPrLGRKWPN1P9ezHka0/5Dz5rE4HXzKqAXAIrGoH0xzZW+j0N1ZbV/REB9dSOTBZU4R4+4TYyJdc8z7k4Ctx9wHoSfqpzveLnq6Z2NQcm316nF6rAmk47eVok+H/BwmkeXcg/2Qag8HGYxkMTRATAZdOwVQwZi0E1aS1dsvHKhvb5xhhvdVuaSPEH+nuhG7jzI9nITjdTAHqxspE=
    before-install:
    - composer self-update
    install:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - cp www/app.php.example www/app.php
    - composer install
    - composer update
    - php bin/console doctrine:database:create
    - php bin/console doctrine:schema:update --force
    - php bin/console doctrine:fixtures:load -n
    before_script:
    - sudo apt-get update
    - sudo apt-get install apache2
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart
    script:
    - php vendor/bin/simple-phpunit
    after_script:
    - mkdir -p build/logs
    - php vendor/bin/php-coveralls --dry-run -v
    - cd build
    - bash copy-to-ftp.sh
  - stage: frontend
    language: node_js
    node_js: '8'
    dist: xenial
    addons:
      chrome: stable
    before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
    - cd wn-frontend
    script:
    - npm install
    - npm run test
    - npm run build
    after_script:
    - mkdir -p ./../build/logs
notifications:
  email:
    recipients:
    - the_weirdo@gmx.net
    on_success: always
