matrix:
  include:
  - stage: backend
    language: php
    php:
    - '7.1'
    sudo: false
    services:
    - mysql
    cache:
      directories:
      - "$HOME/.composer/cache/files"
    env:
    - SYMFONY_VERSION="3.4.*" DB=mysql
    - secure: "NtqXNvBPVeT63r+SEMewdXcVsbWIezPGv8zIDPEr7Y2JM/vQrwqMd1YDoi4JQdbD4IG/qXMHI6bVB4Dr/qfs5urX29ijQ1noMUzrDzmL3nW8aiNPRJLdeSRpoGcHBxQPnh7aCHI1wfAmeHJBd+FFtkRd96oiKEJBFfTMA9EAqbeeiljKcKAR4FdTWVid6z9Q+heszibLV+SltltN1ZzyPwHbGYPDj2569Vwpy2BfY6hVGUJFqLV0OhcfArHkpSUyeWToGm2B/M4weahz1rranML/UdGMMpFcf4L10iJi46uFXa5F84igCxSba+S4IPAkusa7rHuG+kJ3JOVjSdrM/FEG5ELQg0HzTDKPXvQXoaMc4a1aoG8tgaQ48Z4+fkJkvHyDl3beKsBlOUi3ltUMnRMTKt4yRrPWE5LEGmNA3JxDvvu+t0bhHev6mB2D4Mv++zZ3uWEsI2W8RWCCt4qYG607ijyZdQiGIM4eKbfPltphdCR+MQwGoDqA7jmsPAJ1Ylb9i6M9cd8szNwkqyrjhxkSC2MycAADiPGOaptU5lXUv1JLtC6OO5TTAXWHymoNeccFtgxdo9LfzgLlJbxvwBi9Y+LJ62plWnDjG8IX4je9/NGVhGFdfpmj4htQvv05YjzgpEyRlnKM5K1twWQwyS+QOBEfPOd7TZ3vrh+Ux5w="
    before-install:
    - composer self-update
    install:
    - cp app/config/parameters.yml.dist app/config/parameters.yml
    - cp www/app.php.example www/app.php
    - composer install
    - composer update
    - php bin/console doctrine:database:create
    - php bin/console doctrine:schema:update --force
    - php bin/console doctrine:fixtures:load -n
    before_script:
    - sudo apt-get update
    - sudo apt-get install apache2
    - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
    - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
    - sudo service apache2 restart
    script:
    - php vendor/bin/simple-phpunit
    after_script:
    - mkdir -p build/logs
    - php vendor/bin/php-coveralls --dry-run -v
    - cd build
    - bash copy-to-ftp.sh $WERFTNET_BUILD_FTP_KEY
  - stage: frontend
    language: node_js
    node_js: '8'
    dist: xenial
    addons:
      chrome: stable
    before_install:
    - export CHROME_BIN=chromium-browser
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start
    before_script:
    - cd wn-frontend
    script:
    - npm install
    - npm run test
    - npm run build
    after_script:
    - mkdir -p ./../build/logs
notifications:
  email:
    recipients:
    - the_weirdo@gmx.net
    on_success: always