imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        enabled: false
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

security:
    firewalls:
        main:
            http_basic: ~

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     127.0.0.1
        port:     null
        dbname:   WerftnetTest
        user:     test
        password: test
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

swiftmailer:
    disable_delivery: true
