# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.
    # makes classes in src/AppBundle available to be used as services
    AppBundle\:
        resource: '../../src/AppBundle/*'

    # Resolve autowiring conflict with User
    AppBundle\Entity\User\User:
        alias: Symfony\Component\Security\Core\User\UserInterface
        public: false

    user.listener:
        class: AppBundle\EventListener\UserRoleSetter
        tags:
            - { name: doctrine.event_listener, event: prePersist }
    jms_serializer.object_constructor:
        alias: jms_serializer.doctrine_object_constructor
        public: false
    jms_serializer.unserialize_object_constructor:
        class: AppBundle\Serializer\ObjectConstructor
        public: false
    app.security.authentication_handler:
        class: AppBundle\EventListener\AuthenticationHandler
        public: false
        calls:
            - [ 'setEntityManager', [ '@doctrine.orm.entity_manager' ]]
        arguments:
            - '@router'
            - '@session'
    app.security.logout_success_handler:
        class: AppBundle\EventListener\LogoutSuccessHandler
        public: false
    AppBundle\DataFixtures\:
        resource: '../../src/AppBundle/DataFixtures'
        tags: ['doctrine.fixture.orm']